name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'k8s/**'
      - 'k8s-dev/**'
      - 'k8s-prod/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save k8s-eticket
      - run: kubectl apply -f k8s && kubectl apply -f k8s-prod
